import { PrismaClient } from "@/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL!,
});

const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    adapter,
  });

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
}

export interface User {
  id: number;
  name: string;
  email: string;
  role: string;
  status: "Active" | "Inactive";
  department: string;
  jobTitle: string;
  phone: string;
  notes: string;
  accessJustification: string;
  createdAt: string;
}

/*
 * Convert a Prisma User record
 * into the format used by the UI.
 *
 * IMPORTANT:
 * Keep the COMPLETE createdAt
 * timestamp.
 *
 * Do NOT use:
 * .split("T")[0]
 *
 * because that removes the actual
 * creation time.
 */
function toUser(user: {
  id: number;
  name: string;
  email: string;
  role: string;
  status: string;
  department: string;
  jobTitle: string;
  phone: string;
  notes: string;
  accessJustification: string;
  createdAt: Date;
}): User {
  return {
    id: user.id,

    name: user.name,

    email: user.email,

    role: user.role,

    status:
      user.status === "Inactive"
        ? "Inactive"
        : "Active",

    department: user.department,

    jobTitle: user.jobTitle,

    phone: user.phone,

    notes: user.notes,

    accessJustification:
      user.accessJustification,

    /*
     * Preserve real PostgreSQL
     * creation date AND time.
     *
     * Example:
     * 2026-09-24T01:35:42.123Z
     */
    createdAt:
      user.createdAt.toISOString(),
  };
}

/*
 * Get all users.
 */
export async function getUsers(): Promise<User[]> {
  const users =
    await prisma.user.findMany({
      orderBy: {
        id: "asc",
      },
    });

  return users.map(toUser);
}

/*
 * Get one user by ID.
 */
export async function getUserById(
  id: number
): Promise<User | undefined> {
  const user =
    await prisma.user.findUnique({
      where: {
        id,
      },
    });

  return user
    ? toUser(user)
    : undefined;
}

/*
 * Create a new user.
 *
 * createdAt is automatically
 * generated by PostgreSQL/Prisma
 * using @default(now()).
 */
export async function createUser(
  userData: Omit<
    User,
    "id" | "createdAt"
  >
): Promise<User> {
  const user =
    await prisma.user.create({
      data: {
        name:
          userData.name,

        email:
          userData.email,

        role:
          userData.role,

        status:
          userData.status,

        department:
          userData.department,

        jobTitle:
          userData.jobTitle,

        phone:
          userData.phone,

        notes:
          userData.notes,

        accessJustification:
          userData.accessJustification,
      },
    });

  return toUser(user);
}

/*
 * Update an existing user.
 */
export async function updateUser(
  id: number,
  userData: Partial<
    Omit<
      User,
      "id" | "createdAt"
    >
  >
): Promise<User | null> {
  const existingUser =
    await prisma.user.findUnique({
      where: {
        id,
      },
    });

  if (!existingUser) {
    return null;
  }

  const user =
    await prisma.user.update({
      where: {
        id,
      },

      data: {
        ...(userData.name !==
          undefined && {
          name:
            userData.name,
        }),

        ...(userData.email !==
          undefined && {
          email:
            userData.email,
        }),

        ...(userData.role !==
          undefined && {
          role:
            userData.role,
        }),

        ...(userData.status !==
          undefined && {
          status:
            userData.status,
        }),

        ...(userData.department !==
          undefined && {
          department:
            userData.department,
        }),

        ...(userData.jobTitle !==
          undefined && {
          jobTitle:
            userData.jobTitle,
        }),

        ...(userData.phone !==
          undefined && {
          phone:
            userData.phone,
        }),

        ...(userData.notes !==
          undefined && {
          notes:
            userData.notes,
        }),

        ...(userData.accessJustification !==
          undefined && {
          accessJustification:
            userData.accessJustification,
        }),
      },
    });

  return toUser(user);
}

/*
 * Delete one user.
 *
 * UserActivity records will also
 * be deleted automatically because
 * the Prisma relation uses:
 *
 * onDelete: Cascade
 */
export async function deleteUser(
  id: number
): Promise<boolean> {
  const existingUser =
    await prisma.user.findUnique({
      where: {
        id,
      },
    });

  if (!existingUser) {
    return false;
  }

  await prisma.user.delete({
    where: {
      id,
    },
  });

  return true;
}

/*
 * Delete multiple users.
 */
export async function deleteUsers(
  ids: number[]
): Promise<number[]> {
  const uniqueIds = [
    ...new Set(ids),
  ];

  if (uniqueIds.length === 0) {
    return [];
  }

  /*
   * Determine which users actually
   * exist before deleting them.
   *
   * This allows us to return the
   * correct deleted IDs instead of
   * assuming the first N IDs were
   * deleted.
   */
  const existingUsers =
    await prisma.user.findMany({
      where: {
        id: {
          in: uniqueIds,
        },
      },

      select: {
        id: true,
      },
    });

  const existingIds =
    existingUsers.map(
      (user) => user.id
    );

  if (existingIds.length === 0) {
    return [];
  }

  await prisma.user.deleteMany({
    where: {
      id: {
        in: existingIds,
      },
    },
  });

  return existingIds;
}